version: '3.8'

services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
      - ./docker_mapped_output/metabasedb:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: ${DEFAULTDB}
      MB_DB_DBNAME: ${DEFAULTDB}
      MB_DB_PORT: ${PORT}
      MB_DB_USER: ${USER}
      MB_DB_PASS: ${PASSWORD}
      MB_DB_HOST: ${HOST}
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${DBNAME}
    volumes:
      - ./docker_mapped_output/rest_countries_db:/var/lib/postgresql/data:rw
    ports:
      - "5434:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "8080:80"

  python_script:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - pgdatabase

volumes:
  docker_mapped_output:


