version: '3.8'

services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
      - ./docker_mapped_output/metabasedb:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: postgres
      MB_DB_PORT: 5432
      MB_DB_USER: root
      MB_DB_PASS: root
      MB_DB_HOST: pgdatabase
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=countries_db
    volumes:
      - ./docker_mapped_output/rest_countries_db:/var/lib/postgresql/data:rw
    ports:
      - "5434:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"

  python_script:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - pgdatabase

volumes:
  docker_mapped_output:


